version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - yum install -y maven
      - echo Installing AWS CDK...
      - npm install -g aws-cdk
      - echo Installing jq...
      - yum install -y jq

  pre_build:
    commands:
      - echo Logging in to AWS...
      - aws sts get-caller-identity
      - echo Running Maven clean install...
      - mvn clean install

  build:
    commands:
      - echo Synthesizing CDK app...
      - cdk synth
      - echo Deploying CDK app...
      - cdk deploy --require-approval never --outputs-file cdk_output.json
      - cat cdk_output.json

artifacts:
  files:
    - cdk.out/**/*